CREATE TABLE EMPL(
    EID CHAR(3 BYTE) CONSTRAINT PKEID PRIMARY KEY, --기본키
    ENAME VARCHAR2(20 BYTE)CONSTRAINT NENAME NOT NULL, --눌값안됨
    ENO CHAR(14 BYTE) CONSTRAINT UENO UNIQUE, --중복안됨
    EMAIL VARCHAR2(25 BYTE)NOT NULL CONSTRAINT UEMAIL UNIQUE,  --ENO 눌값안되고 중복안되고  
    PHONE VARCHAR2(12 BYTE),
    HIREDATE  DATE DEFAULT sysdate,
    JID CHAR(2 BYTE),
    SALARY NUMBER,
    BOUNSPCI NUMBER,
    MARRIAGE CHAR(1 BYTE) DEFAULT 'N',
    MID CHAR(3 BYTE),
    DID CHAR(2 BYTE));
    
DROP TABLE EMPL;
--JID 외래키 설정
ALTER TABLE EMPL ADD CONSTRAINT FKJID FOREIGN KEY(JID) REFERENCES JOB(JID) ON DELETE SET NULL;

--MARRIGE컬럼 y,n만 들어가게하기
ALTER TABLE EMPL ADD CONSTRAINT CHK CHECK(MARRIAGE IN('y','n'));

--MID컬럼 제약조건
ALTER TABLE EMPL ADD CONSTRAINT FKMID FOREIGN KEY(MID) REFERENCES EMPL(EID) ON DELETE SET NULL;

--DID 컬럼 제약조건
ALTER TABLE EMPL ADD CONSTRAINT FKDID FOREIGN KEY(DID) REFERENCES DEPARTMENT ON DELETE CASCADE;

COMMENT ON COLUMN EMPL.EID IS '사번';
COMMENT ON COLUMN EMPL.ENAME IS '사원명';
COMMENT ON COLUMN EMPL.ENO IS '주민번호';
COMMENT ON COLUMN EMPL.EMAIL IS '이메일';
COMMENT ON COLUMN EMPL.PHONE IS '전화번호';
COMMENT ON COLUMN EMPL.HIREDATE IS '입사일';
COMMENT ON COLUMN EMPL.JID IS '직급번호';
COMMENT ON COLUMN EMPL.SALARY IS '급여';
COMMENT ON COLUMN EMPL.BONUSPCI IS '보너스포인트';
COMMENT ON COLUMN EMPL.MARRIAGE IS '결혼여부';
COMMENT ON COLUMN EMPL.MID IS '관리자사번';
COMMENT ON COLUMN EMPL.DID IS '부서번호';


CREATE TABLE DEPARTMENT(
    DEPTNO NUMBER CONSTRAINT dept_pk PRIMARY KEY,
    DEPTNAME NVARCHAR2(10) NOT NULL
);

CREATE TABLE EMPLOYEE(
    EMPNO NUMBER PRIMARY KEY,
    EMPNAME NVARCHAR2(10) NOT NULL,
    DEPTNO NUMBER REFERENCES DEPARTMENT(DEPTNO)
);
DROP TABLE EMPLOYEE;

SELECT* FROM USER_CONSTRAINTS;

SELECT EMPNO, EMPNAME, D.DEPTNO, DEPTNAME FROM EMPLOYEE E, DEPARTMENT D
    WHERE E.DEPTNO = D.DEPTNO;
SELECT EMPNO, EMPNAME, D.DEPTNO,DEPTNAME FROM EMPLOYEE E INNER JOIN DEPARTMENT D ON D.DEPTNO =E.DEPTNO;

ALTER TABLE EMPL DROP CONSTRAINT PKEID; 
ALTER TABLE EMPLOYEE ADD CONSTRAINT eno_pk PRIMARY KEY(EMPNO,EMPNAME);

CREATE TABLE PRODUCT(
    PNAME VARCHAR2(20),
    PRICE NUMBER,
    PSTATE CHAR(1),
    PCOMMENT VARCHAR2(100));
    
--확인--
DESC  PRODUCT;

INSERT INTO PRODUCT VALUES('갤럭시노트10',1950000,'A','사전예약 시행중');
INSERT INTO PRODUCT VALUES('MACBOOK AIR',1500000,'B','맥북 프로보다 가볍게 사용할 수 있음');
INSERT INTO PRODUCT VALUES('LG V7',780000,'C','카메라 성능이 세계적으로 우수함');

--확인--
SELECT * FROM PRODUCT;

SELECT * FROM user_constraints WHERE OWNER='SCOTT';
GRANT CREATE VIEW TO SCOTT;
CREATE OR REPLACE FORCE VIEW test03 AS(
    SELECT * FROM emp)WITH READ ONLY;
    





DROP TABLE DEPARTMENT;

--1번
CREATE TABLE DEPARTMENT(
    DEPTNO NUMBER CONSTRAINT PK_DEPTNO PRIMARY KEY,
    DEPTNAME VARCHAR2(30) CONSTRAINT NN_DEPTNM NOT NULL     
        CONSTRAINT UN_DEPTNM UNIQUE
    );
    --확인--
    SELECT* FROM user_constraints ;
--2번
CREATE TABLE EMPLOYEE(
    EMPNO NUMBER CONSTRAINT PK_EMPNO PRIMARY KEY,
    EMPNAME VARCHAR2(10) CONSTRAINT NN_EMPNM NOT NULL,    
    DEPTNO NUMBER NOT NULL,
    SALARY NUMBER DEFAULT 1000000 CONSTRAINT CHK_EMPSAL CHECK(SALARY>0),
    GENDER VARCHAR2(1) CONSTRAINT CHK_EMPGEN CHECK(GENDER IN('M','F')),
    --외래키 설정
    CONSTRAINT FK_DEPTNO FOREIGN KEY(DEPTNO) REFERENCES DEPARTMENT(DEPTNO)   
    );


SELECT TO_CHAR(12345,'99,999') FROM DUAL;
SELECT TO_DATE('20201120') FROM DUAL;
SELECT deptno,count(*) FROM EMP GROUP BY DEPTNO;

DESC EMP;

SELECT ENAME, JOB, DECODE(DEPTNO,
    10, '회계팀',
    20, '연구팀',
    30, '무슨팀이지',
    40, '기획팀') as 부서명
    FROM emp;

CREATE USER scott2 IDENTIFIED BY tiger; 
--롤 생성
CREATE ROLE soc_role;
--롤에 권한부여
GRANT CONNECT,RESOURCE TO soc_role;
--롤을 계정에 부여
GRANT soc_role TO scott;

CREATE INDEX soc_idx ON emp(empno);

SELECT * FROM emp WHERE sal< ANY(100,200,3000);
SELECT * FROM emp WHERE sal< SOME(100,200,3000);
SELECT * FROM emp WHERE sal< (SELECT MAX(sal) FROM EMP  WHERE sal IN(100,200,3000));
