SELECT E.ANIMAL_ID,E.ANIMAL_TYPE, E.NAME FROM
    (SELECT * FROM ANIMAL_INS WHERE SUBSTR(SEX_UPON_INTAKE,1,6) = 'Intact')E,
    (SELECT * FROM ANIMAL_OUTS WHERE NOT (SUBSTR(SEX_UPON_OUTCOME,1,6) = 'Intact'))R
WHERE E.ANIMAL_ID = R.ANIMAL_ID ORDER BY E.ANIMAL_ID
